apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  name: {{ include "capi-aws-cluster.fullname" . }}-master
  labels:
    {{- include "capi-aws-cluster.labels" . | nindent 4 }}
    cluster.x-k8s.io/control-plane: "true"
    cluster.x-k8s.io/cluster-name: {{ include "capi-aws-cluster.fullname" . }}
spec:
  version: {{ .Values.master.version }}
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: {{ include "capi-aws-cluster.fullname" . }}-master
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: AWSMachine
    name: {{ include "capi-aws-cluster.fullname" . }}-master
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSMachine
metadata:
  name: {{ include "capi-aws-cluster.fullname" . }}-master
  labels:
    {{- include "capi-aws-cluster.labels" . | nindent 4 }}
spec:
  instanceType: {{ .Values.master.size }}
  rootDeviceSize: {{ .Values.master.rootDeviceSize }}
  availabilityZone: {{ .Values.cluster.region }}a
  # This IAM profile is part of the pre-requisites.
  iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"
  # Change this value to a valid SSH Key Pair present in your AWS Account.
  sshKeyName: {{ .Values.master.sshKeyName }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: {{ include "capi-aws-cluster.fullname" . }}-master
  labels:
    {{- include "capi-aws-cluster.labels" . | nindent 4 }}
spec:
  # For more information about these values,
  # refer to the Kubeadm Bootstrap Provider documentation.
  initConfiguration:
    nodeRegistration:
      name: {{`'{{ ds.meta_data.hostname }}'`}}
      kubeletExtraArgs:
        cloud-provider: aws
  clusterConfiguration:
    apiServer:
      extraArgs:
        cloud-provider: aws
    controllerManager:
      extraArgs:
        cloud-provider: aws
