apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . |  sha256sum  }}
    spec:
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      imagePullSecrets:
      - name: dockercfg
      affinity:
        nodeAffinity:
{{ toYaml .Values.nodeAffinity | indent 10 }}
      containers:
      - name: fluentd-shipper
        image: {{ .Values.image }}
        command:
          - /bin/bash
          - -c
          - "envtpl < /fluentd/etc/fluent.tpl > /${FLUENTD_CONF} && exec fluentd -v -c /${FLUENTD_CONF} -p /fluentd/plugins ${FLUENTD_OPT}"
        env:
{{ toYaml .Values.env | indent 10 }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker
        - name: fluentdconfig
          mountPath: /fluentd/etc
        - name: runlog
          mountPath: /var/log/journald
        - name: cachepath
          mountPath: /srv/fluentd/cache
      terminationGracePeriodSeconds: 30
      serviceAccountName: fluentd
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker
      - name: fluentdconfig
        configMap:
          name: {{ .Chart.Name }}-config
      - name: runlog
        hostPath:
          path: /run/log
      - name: cachepath
        hostPath:
          path: /srv/fluentd/cache
