{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    k8s-app: {{ .Chart.Name }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  endpoints:
  - port: metrics
{{- end }}
