apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elasticsearch-template.fullname" . }}
  labels:
{{ include "elasticsearch-template.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.templates }}
  {{ $key }}:{{ toYaml $value | default "{}" | indent 2 }}
{{- end -}}
