{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "elasticsearch-template.serviceAccountName" . }}
  labels:
{{ include "elasticsearch-template.labels" . | indent 4 }}
{{- end -}}
