apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oidc-starter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oidc-starter.name" . }}
    helm.sh/chart: {{ include "oidc-starter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oidc-starter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oidc-starter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /bin/oidc-starter
          - --listen=http://0.0.0.0:80
          - --client-id=$(CLIENT_ID)
          - --client-secret=$(CLIENT_SECRET)
          {{- if .Values.oidc_starter.issuer }}
          - --issuer={{ .Values.oidc_starter.issuer }}
          {{- end }}
          {{- if .Values.oidc_starter.redirectURI }}
          - --redirect-uri={{ .Values.oidc_starter.redirectURI }}
          {{- end }}
          {{- if .Values.oidc_starter.baseRedirectURI }}
          - --base-redirect-uri={{ .Values.oidc_starter.baseRedirectURI }}
          {{- end }}
          {{- if .Values.oidc_starter.debug }}
          - --debug
          {{- end }}
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          env:
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "oidc-starter.fullname" . }}
                key: client-id
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "oidc-starter.fullname" . }}
                key: client-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
