apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oidc-starter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oidc-starter.name" . }}
    helm.sh/chart: {{ include "oidc-starter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  client-id: {{ .Values.oidc_starter.clientId }}
  client-secret: {{ .Values.oidc_starter.clientSecret }}
