{{- if .Values.data.exposeHttp }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.data.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.data.fullname" . }}
spec:
  ports:
    - name: http
      port: 9200
      targetPort: http
  selector:
    app: {{ template "elasticsearch.name" . }}
    component: "{{ .Values.data.name }}"
    release: {{ .Release.Name }}
  type: {{ .Values.data.serviceType }}
{{- end }}
