{{- if .Values.master.service.create }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.master.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.fullname" . }}-discovery
spec:
{{- if and ( eq .Values.master.replicas 0.0 ) ( .Values.data.masterEligible ) ( .Values.data.exposeHttp ) }}
  type: {{ .Values.data.serviceType }}
{{- else }}
  clusterIP: None
{{- end }}
  ports:
    - name: transport
      port: 9300
      targetPort: transport
{{- if or ( .Values.master.service.exposeHttp ) ( .Values.data.exposeHttp ) }}
    - name: http
      port: 9200
      targetPort: http
{{- end }}
  selector:
    app: {{ template "elasticsearch.name" . }}
    release: {{ .Release.Name }}
{{- if not .Values.data.podLabels.component }}
  {{- if and ( eq .Values.master.replicas 0.0 ) ( .Values.data.masterEligible ) }}
    component: "{{ .Values.data.name }}"
  {{- else }}
    component: "{{ .Values.master.name }}"
  {{- end }}
{{- end }}
{{- if and ( eq .Values.master.replicas 0.0 ) ( .Values.data.masterEligible ) ( .Values.data.podLabels ) }}
{{ toYaml .Values.data.podLabels | indent 4 }}
{{- end }}

{{- end }}
