apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dex-k8s-authenticator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dex-k8s-authenticator.name" . }}
    helm.sh/chart: {{ include "dex-k8s-authenticator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  config.yaml: |
    {{- with .Values.dexK8sAuthenticator }}
    listen: http://0.0.0.0:{{ .listen_port }}
    web_path_prefix: {{ .web_path_prefix }}
    kubectl_version: {{ .kubectl_version }}
    debug: {{ .debug }}
    {{- if .trusted_root_ca }}
    trusted_root_ca:
    {{- toYaml .trusted_root_ca | nindent 4 }}
    {{- end }}
    {{- if .idp_ca_pem }}
    idp_ca_pem: |
    {{- .idp_ca_pem | nindent 6 }}
    {{- end }}
    {{- if .logoUrl }}
    logo_uri: {{ .logoUrl }}
    {{- end }}
    {{- if .idpCaURI }}
    idp_ca_uri: {{ .idpCaURI }}
    {{- end }}
    {{- if .idpCaPem }}
    idp_ca_pem: {{ .idpCaPem }}
    {{- end }}
    {{- if and .tlsCert .tlsKey }}
    tls_cert: "{{ .tlsCert }}"
    tls_key: "{{ .tlsKey }}"
    {{- end }}
    clusters:
    {{- toYaml .clusters | nindent 4 }}
    {{- end }}
