apiVersion: v1
kind: Service
metadata:
  name: {{ include "dex-k8s-authenticator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dex-k8s-authenticator.name" . }}
    helm.sh/chart: {{ include "dex-k8s-authenticator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.servicemonitor.port }}
      targetPort: http
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "dex-k8s-authenticator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
