{{- if .Values.extraService.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.extraService.annotations }}
  annotations:
{{ toYaml .Values.extraService.annotations | indent 4 }}
{{- end }}
  name: {{ template "fluent-bit.fullname" . }}
  labels:
    app: {{ template "fluent-bit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.extraService.labels }}
  {{- range $key, $value := .Values.extraService.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.extraService.type}}
  sessionAffinity: None
  ports:
{{ toYaml .Values.extraService.ports | indent 2 }}
  selector:
    app: {{ template "fluent-bit.name" . }}
    release: {{ .Release.Name }}
{{- end }}
