apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "promxy.fullname" . }}
  labels:
    {{- include "promxy.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.promxy.config | nindent 4 }}
