---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      affinity:
        nodeAffinity:
{{ toYaml .Values.nodeAffinity | indent 10 }}
      containers:

      - name: legacy-cert-manager
        image: {{ .Values.image }}
        ports:
        - containerPort: 9375
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-aws-secret
        env:
{{ toYaml .Values.env | indent 10 }}
        volumeMounts:
{{ toYaml .Values.volumeMounts | indent 10 }}
      restartPolicy: Always
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
