---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws-secret
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.version }}
    release: {{ .Relese.Name }}
data:
  AWS_ACCESS_KEY_ID: |-
    {{ .Values.aws_key | b64enc }}
  AWS_SECRET_ACCESS_KEY: |-
    {{ .Values.aws_secret | b64enc }}
