---
apiVersion: v1
kind: Service
metadata:
  name: legacy-cert-manager
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    service: metrics
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.port }}

