---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.secretName }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.targetNamespaces }}
    rumored: "yes"
  annotations:
    rumors/namespaces: {{ .Values.targetNamespaces }}
{{- end }}
data:
{{- if .Values.gcr }}
  .dockerconfigjson: {{ printf "{\"auths\": {\"gcr.io\": {\"auth\": \"%s\"}}}" (printf "_json_key:%s" (toJson $.Values.token) | b64enc) }}
{{- else }}
  .dockerconfigjson: {{ .Values.token }}
{{- end }}
