---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.secretName }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    rumored: "yes"
  annotations:
    rumors/namespaces: {{ .Values.targetNamespaces }}
data:
  .dockerconfigjson: {{ .Values.token }}