{{- $fullName := include "cert-issuer.fullname" . -}}
apiVersion: cert-manager.io/v1alpha2
kind: {{ .Values.kind }}
metadata:
  name: {{ template "cert-issuer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cert-issuer.name" . }}
    helm.sh/chart: {{ include "cert-issuer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  acme:
    server: {{ .Values.server }}
    email: {{ .Values.email }}
    privateKeySecretRef:
    {{- if .Values.privateKeySecretRef }}
      {{- toYaml .Values.privateKeySecretRef | nindent 6 }}
    {{- else }}
      name: {{ $fullName }}
    {{- end }}
    solvers:
      {{- toYaml .Values.solvers | nindent 6 }}
