{{- if and ( .Values.vmstorage.backupSidecar.enabled ) ( .Values.vmstorage.backupSidecar.awsCredentials ) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-s3-credentials
  labels:
    app.kubernetes.io/name: aws-s3-credentials
    app.kubernetes.io/component: vmstorage
    {{- include "victoria-metrics.common-labels" . | nindent 4 }}
data:
{{- with .Values.vmstorage.backupSidecar.awsCredentials }}
  aws-access-key-id: {{ .accessKeyId | b64enc }}
  aws-secret-access-key: {{ .secretAccessKey | b64enc }}
{{- end }}
{{- end }}
