{{- if and ( .Values.vminsert.enabled ) ( .Values.vminsert.serviceMonitor.enabled ) -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "victoria-metrics.fullname" . }}-vminsert
{{- if .Values.vminsert.serviceMonitor.namespace }}
  namespace: {{ .Values.vminsert.serviceMonitor.namespace }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "victoria-metrics.fullname" . }}-vminsert
    app.kubernetes.io/component: vminsert
    {{ include "victoria-metrics.common-labels" . | nindent 4 }}
  {{- with .Values.vminsert.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "victoria-metrics.fullname" . }}-vminsert
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: vminsert
  endpoints:
  - port: http
{{- end }}
