{{- if .Values.vmstorage.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "victoria-metrics.fullname" . }}-vmstorage
  labels:
    app.kubernetes.io/name: {{ include "victoria-metrics.fullname" . }}-vmstorage
    app.kubernetes.io/component: vmstorage
    {{ include "victoria-metrics.common-labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.vmstorage.replicaCount }}
  serviceName: {{ include "victoria-metrics.fullname" . }}-vmstorage
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "victoria-metrics.fullname" . }}-vmstorage
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: vmstorage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "victoria-metrics.fullname" . }}-vmstorage
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: vmstorage
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/awscreds-secret.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.vmstorage.terminationGracePeriodSeconds | int }}
    {{- with .Values.vmstorage.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: vmstorage
          image: "{{ .Values.vmstorage.image.repository }}:{{ if not .Values.vmstorage.image.tag }}{{ .Chart.AppVersion }}{{ else }}{{ .Values.vmstorage.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.vmstorage.image.pullPolicy }}
          args:
            - --storageDataPath=/vmstorage-data
            - {{ printf "%s=%d" "--retentionPeriod" (int .Values.vmstorage.retentionPeriod) | quote }}
          {{- range $key, $value := .Values.vmstorage.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8482
              protocol: TCP
            - name: vminsert
              containerPort: 8400
              protocol: TCP
            - name: vmselect
              containerPort: 8401
              protocol: TCP
        {{- if .Values.vmstorage.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.vmstorage.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.vmstorage.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.vmstorage.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.vmstorage.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.vmstorage.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.vmstorage.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.vmstorage.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.vmstorage.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.vmstorage.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.vmstorage.readinessProbe.failureThreshold }}
        {{- end }}
          resources:
            {{- toYaml .Values.vmstorage.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /vmstorage-data
              {{- if .Values.vmstorage.persistence.enabled }}
              name: {{ .Values.vmstorage.persistence.name }}
              {{- else }}
              name: vmstorage-data
              {{- end }}
        {{- if .Values.vmstorage.backupSidecar.enabled }}
        {{- with .Values.vmstorage.backupSidecar }}
        - name: backup-sidecar
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- if .extraArgs }}
          args:
          {{ toYaml .extraArgs }}
          {{- end }}
          ports:
            - name: vmbackup
              containerPort: {{ .containerPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .env }}
            - name: {{ $key | quote }}
              value: {{ tpl $value $ | quote }}
            {{- end }}
            {{- if .awsCredentials }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: aws-secret-access-key
            {{- end }}
        {{- if .livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: vmbackup
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: vmbackup
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .readinessProbe.timeoutSeconds }}
            successThreshold: {{ .readinessProbe.successThreshold }}
            failureThreshold: {{ .readinessProbe.failureThreshold }}
        {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
        {{- end }}
          volumeMounts:
            - mountPath: /vmstorage-data
              {{- if .Values.vmstorage.persistence.enabled }}
              name: {{ .Values.vmstorage.persistence.name }}
              {{- else }}
              name: vmstorage-data
              {{- end }}
        {{- end }}
      {{- with .Values.vmstorage.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.vmstorage.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.vmstorage.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if not .Values.vmstorage.persistence.enabled }}
      volumes:
        - name: vmstorage-data
          hostPath:
            path: {{ .Values.vmstorage.nonPersistence.hostPath.path }}
            type: {{ .Values.vmstorage.nonPersistence.hostPath.type }}
      {{- end }}
  {{- if .Values.vmstorage.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.vmstorage.persistence.name }}
      spec:
        accessModes:
          - {{ .Values.vmstorage.persistence.accessMode }}
        {{- if hasKey .Values.vmstorage.persistence "storageClass" }}
        storageClassName: {{ .Values.vmstorage.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.vmstorage.persistence.size | quote }}
  {{- end }}
{{- end }}
