# Default values for cert-issuer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

kind: Issuer
server: "https://acme-v02.api.letsencrypt.org/directory"
email: "user@example.com"
privateKeySecretRef: {}

solvers:
  # An empty 'selector' means that this solver matches all domains
  dns01: {}
    # selector: {}
  http01: {}
    # selector: {}
    # ingress:
    #   class: nginx
