{{ if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  run.yml: |
{{ .Values.config | indent 4 }}
{{ end }}
