---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      restartPolicy: Always
      containers:
      - name: monitoring
        image: {{ .Values.image }}
        ports:
        - name: metrics
          containerPort: 9400
        livenessProbe:
          httpGet:
            path: /
            port: 9400
          initialDelaySeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 9400
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{ if .Values.secretEnv }}
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-aws-secret
{{ end }}
{{ if .Values.config }}
        volumeMounts:
        - name: config-volume
          mountPath: /opt/monitoring
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-configmap
{{ end }}
