{{ if .Values.secretEnv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws-secret
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  {{- range $name, $value := .Values.secretEnv }}
  {{ $name }}: '{{ $value | b64enc }}'
  {{- end }}
{{ end }}
