{{- if .Values.createServiceMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  jobLabel: app
  endpoints:
  - port: metrics
    interval: 30s
  selector: 
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
