replicas: 1
port: "9375"
image: anchorfree/cert-manager:v0.1.0

aws_key: "xxx"
aws_secret: "xxx"
env:
- name: LEGO_PATH
  value: "/usr/local/bin/lego"
- name: LETSENCRYPT_EMAIL
  value: "uniq-email@per.account"
- name: AWS_REGION
  value: "us-east-1"
- name: DOMAINS_FILE
  value: "s3://some-bucket/domains/prod.txt"
- name: STORE_DIR
  value: "/certs"

volumeMounts:
- mountPath: /certs
  name: cert-volume
volumes:
- name: cert-volume
  emptyDir: {}

nodeAffinity: {}
tolerations: []

s3push:
  image: anchorfree/s3push
  tag: v0.1.8
  env:
    - name: S3_BUCKET
      value: "s3://some-bucket"
    - name: LOCAL_DIRS
      value: "/certs/certificates /certs/accounts"
    - name: AWS_REGION
      value: "us-east-1"
