replicas: 1
port: "9375"
image: anchorfree/cert-manager:v0.0.7
aws_key: "xxx"
aws_secret: "xxx"
s3push:
  image: anchorfree/s3push
  tag: v0.1.7
env:
- name: LEGO_PATH
  value: "/usr/local/bin/lego"
- name: LETSENCRYPT_EMAIL
  value: "uniq-email@per.account"
- name: AWS_REGION
  value: "us-east-1"
- name: S3_BUCKET
  value: "s3://some-bucket"
- name: DOMAINS_FILE
  value: "s3://some-bucket/domains/prod.txt"
- name: LOCAL_DIR
  value: "/certs"
volumeMounts:
- mountPath: /certs
  name: cert-volume
volumes:
- name: cert-volume
  emptyDir: {}
nodeAffinity: {}
tolerations: []
