{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "prometheus-cloudwatch-exporter.name" . }}
    chart: {{ template "prometheus-cloudwatch-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["secrets","configmap"]
    resourceNames:
{{- $root := . -}}
{{- range $region, $options := .Values.config }}
      - {{ $root.Release.Name }}-{{ $region }}
{{- end }}
    verbs: ["get"]
{{- end }}
