{{- $root := . -}}
{{- range $region, $options := .Values.config }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "prometheus-cloudwatch-exporter.fullname" $root }}-{{ $region }}
  labels:
    app: {{ template "prometheus-cloudwatch-exporter.name" $root }}
    chart: {{ template "prometheus-cloudwatch-exporter.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
    region: {{ $region }}
spec:
  replicas: {{ $root.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "prometheus-cloudwatch-exporter.name" $root }}
      release: {{ $root.Release.Name }}
      region: {{ $region }}
  template:
    metadata:
      labels:
        app: {{ template "prometheus-cloudwatch-exporter.name" $root }}
        release: {{ $root.Release.Name }}
        region: {{ $region }}
      annotations:
        {{ if $root.Values.aws.role}}iam.amazonaws.com/role: {{ $root.Values.aws.role }}{{ end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $root | sha256sum }}
    spec:
      containers:
        - name: {{ $root.Chart.Name }}
        {{- if not $root.Values.aws.role }}
        {{- if $root.Values.aws.secret.name }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: access_key
                  name: {{ $root.Values.aws.secret.name }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secret_key
                  name: {{ $root.Values.aws.secret.name }}
          {{- if $root.Values.aws.secret.includesSessionToken }}
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  key: security_token
                  name: {{ $root.Values.aws.secret.name }}
          {{- end }}
        {{- else if and $root.Values.aws.aws_secret_access_key $root.Values.aws.aws_access_key_id }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws_access_key_id
                  name: {{ template "prometheus-cloudwatch-exporter.fullname" $root }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws_secret_access_key
                  name: {{ template "prometheus-cloudwatch-exporter.fullname" $root }}
          {{- end }}
          {{- end }}
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          ports:
            - name: container-port
              containerPort: 9106
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: container-port
            initialDelaySeconds: {{ $root.Values.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{ $root.Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $root.Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ $root.Values.livenessProbe.successThreshold }}
            failureThreshold: {{ $root.Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /-/ready
              port: container-port
            initialDelaySeconds: {{ $root.Values.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{ $root.Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $root.Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ $root.Values.readinessProbe.successThreshold }}
            failureThreshold: {{ $root.Values.readinessProbe.failureThreshold }}
          resources:
{{ toYaml $root.Values.resources | indent 12 }}
          volumeMounts:
            - name: vol-prometheus-cloudwatch-exporter
              mountPath: /config
     {{- with $root.Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $root.Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $root.Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ template "prometheus-cloudwatch-exporter.fullname" $root }}-{{ $region }}
        name: vol-prometheus-cloudwatch-exporter

{{- end }}
