{{- if .Values.distributor.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.fullname" . }}-distributor
  labels:
    app.kubernetes.io/name: {{ include "cortex.name" . }}
    helm.sh/chart: {{ include "cortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: distributor
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.distributor.service.type }}
  {{- if and .Values.distributor.service.clusterIP ( eq .Values.distributor.service.type "ClusterIP" ) }}
  clusterIP: {{ .Values.distributor.service.clusterIP }}
  {{- end }}
  ports:
  {{- if default .Values.cortex.server_http_listen_port .Values.distributor.server_http_listen_port }}
  - port: {{ .Values.distributor.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  {{- end }}
  {{- if default .Values.cortex.server_grpc_listen_port .Values.distributor.server_grpc_listen_port }}
  - port: {{ .Values.distributor.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  {{- end }}
  {{- if .Values.distributor.servicemonitor.enabled }}
  - port: {{ .Values.distributor.servicemonitor.port }}
    targetPort: http
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "cortex.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: distributor
{{- end }}
