{{- if .Values.ingester.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.fullname" . }}-ingester
  labels:
    app.kubernetes.io/name: {{ include "cortex.name" . }}
    helm.sh/chart: {{ include "cortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ingester
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.ingester.service.type }}
  ports:
  - port: {{ .Values.ingester.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.query_frontend.service.grpc_port }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  {{- if .Values.ingester.servicemonitor.enabled }}
  - port: {{ .Values.ingester.servicemonitor.port }}
    targetPort: http
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "cortex.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ingester
{{- end }}
