{{- if .Values.ingester.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cortex.fullname" . }}-ingester
  labels:
    app.kubernetes.io/name: {{ include "cortex.name" . }}
    helm.sh/chart: {{ include "cortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ingester
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ingester.replicaCount }}
  minReadySeconds: 120
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cortex.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ingester
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cortex.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ingester
    spec:
      terminationGracePeriodSeconds: 2400
      containers:
      - name: ingester
        image: "{{ .Values.ingester.image.repository }}:{{ .Values.ingester.image.tag }}"
        imagePullPolicy: {{ .Values.ingester.image.pullPolicy }}
        args:
        - -log.level=info
        - -server.http-listen-port=80
        - -server.grpc-listen-port=9095
        - -ingester.num-tokens={{ .Values.global.ingester.num_tokens }}
        - -ingester.join-after=30s
        - -ingester.search-pending-for=2m
        - -ingester.claim-on-rollout=true
        - -ingester.chunk-encoding=3
        - -ingester.normalise-tokens=true
        - -ingester.max-chunk-idle={{ .Values.global.ingester.max_chunk_idle }}
        - -ingester.retain-period=10m10s
        - -ingester.max-series-per-user={{ .Values.global.ingester.max_series_per_user }}
        - -ingester.max-series-per-metric={{ .Values.global.ingester.max_series_per_metric }}
        - -ingester-client.expected-timeseries=1000     # to match setting in queue config
        - -ingester-client.expected-samples-per-series=2 # default of 10 is way too high
        - -validation.reject-old-samples={{ .Values.global.validation.reject_old_samples }}
        - -validation.max-label-names-per-series=25
        - -consul.hostname={{ .Values.global.consul.hostname }}
        - -s3.url={{ .Values.global.s3.url }}
        - -dynamodb.url={{ .Values.global.dynamodb.url }}
        - -dynamodb.original-table-name={{ .Values.global.dynamodb.original_table_name }}
        - -dynamodb.use-periodic-tables=false
        - -dynamodb.v9-schema-from=2019-01-01
        - -dynamodb.periodic-table.from=2030-01-01
        - -distributor.ingestion-rate-limit=2500000
        - -distributor.ingestion-burst-size=5000000
        - -memcached.hostname={{ .Values.global.memcached.hostname }}
        - -memcached.service={{ .Values.global.memcached.service }}
        - -memcached.expiration=24h
        - -store.index-cache-read.memcached.hostname={{ .Values.global.store.index_cache_read.memcached.hostname }}
        - -store.index-cache-read.memcached.service={{ .Values.global.store.index_cache_read.memcached.service }}
        - -store.index-cache-read.memcached.expiration=24h
        - -store.index-cache-write.memcached.hostname={{ .Values.global.store.index_cache_write.memcached.hostname }}
        - -store.index-cache-write.memcached.service={{ .Values.global.store.index_cache_write.memcached.service }}
        - -store.index-cache-write.memcached.expiration=24h
        - -cache.enable-fifocache=true
        - -event.sample-rate=1000
        env:
        - name: GOGC
          value: "60"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: grpc
          containerPort: 9095
          protocol: TCP
        {{/*livenessProbe:*/}}
          {{/*httpGet:*/}}
            {{/*path: /ready*/}}
            {{/*port: http*/}}
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          {{- toYaml .Values.ingester.resources | nindent 10 }}
      {{- with .Values.ingester.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.ingester.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ingester.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
