{{- if .Values.nginx.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cortex.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "cortex.name" . }}
    helm.sh/chart: {{ include "cortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: nginx
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cortex.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cortex.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      {{- if .Values.nginx.servicemonitor.enabled }}
      - name: metrics
        image: "{{ .Values.nginx.servicemonitor.exporter.repository }}:{{ .Values.nginx.servicemonitor.exporter.tag }}"
        imagePullPolicy: {{ .Values.nginx.servicemonitor.exporter.pullPolicy }}
        ports:
        - name: metrics
          containerPort: 9113
          protocol: TCP
        resources:
        {{- toYaml .Values.nginx.servicemonitor.exporter.resources | nindent 10 }}
      {{- end }}
      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          {{- toYaml .Values.nginx.resources | nindent 10 }}
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ include "cortex.fullname" . }}-nginx
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
