{{- if .Values.nginx.enabled -}}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "cortex.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "cortex.name" . }}
    helm.sh/chart: {{ include "cortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: nginx
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |-
    worker_processes      auto;
    error_log             /dev/stderr;
    pid                   /tmp/nginx.pid;
    worker_rlimit_nofile  8192;

    events {
      use                 epoll;
      worker_connections  4096;
      multi_accept        on;
    }

    http {
      default_type application/octet-stream;
      # log_format json_combined escape=json '{'
      #   '"time_local":'      '"$time_local",'
      #   '"remote_addr":'     '"$remote_addr",'
      #   '"remote_user":'     '"$remote_user",'
      #   '"request":'         '"$request",'
      #   '"status":'          '"$status",'
      #   '"body_bytes_sent":' '"$body_bytes_sent",'
      #   '"request_time":'    '"$request_time",'
      #   '"http_referrer":'   '"$http_referer",'
      #   '"http_user_agent":' '"$http_user_agent"'
      # '}';

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log                /dev/stdout main;
      sendfile                  on;
      tcp_nopush                on;
      tcp_nodelay               on;
      resolver                  coredns.kube-system.svc.cluster.local;
      reset_timedout_connection on;

      server {
        listen            8080  default;
        proxy_set_header  X-Scope-OrgID 0;

        location = /api/prom/push {
          proxy_pass    http://{{ include "cortex.fullname" . }}-distributor.{{ .Release.Namespace }}.svc.cluster.local$request_uri;
        }

        location ~ /api/prom/.* {
          proxy_pass    http://{{ include "cortex.fullname" . }}-query-frontend.{{ .Release.Namespace }}.svc.cluster.local$request_uri;
        }

        location /healthz {
          return 200    '{"healthy":"ok"}';
          access_log    off;
        }
        {{ if .Values.nginx.servicemonitor.enabled }}
        location = /stub_status {
          stub_status   on;
          access_log    off;
          allow         127.0.0.1;
          deny          all;
        }
        {{ end }}
      }
    }
{{- end }}
