{{- if .Values.ruler.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cortex.fullname" . }}-ruler
  labels:
    app.kubernetes.io/name: {{ include "cortex.name" . }}
    helm.sh/chart: {{ include "cortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ruler
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ruler.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cortex.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ruler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cortex.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ruler
    spec:
      containers:
      - name: ruler
        image: "{{ .Values.ruler.image.repository }}:{{ .Values.ruler.image.tag }}"
        imagePullPolicy: {{ .Values.ruler.image.pullPolicy }}
        args:
        - -log.level=info
        - -server.http-listen-port=80
        - -ruler.configs.url=http://{{ include "cortex.fullname" . }}-configs.{{ .Release.Namespace }}.svc.cluster.local:80
        - -ruler.alertmanager-url=http://{{ include "cortex.fullname" . }}-alertmanager.{{ .Release.Namespace }}.svc.cluster.local/api/prom/alertmanager/
        - -consul.hostname={{ .Values.global.cortex.consulHostname }}
        - -s3.url={{ .Values.global.cortex.s3URL }}
        - -ingester.max-series-per-metric={{ .Values.global.ingester.max_series_per_metric }}
        - -dynamodb.original-table-name=cortex-index
        - -dynamodb.use-periodic-tables=false
        - -dynamodb.url={{ .Values.global.cortex.dynamodbURL }}
        - -dynamodb.v9-schema-from=2019-01-01
        - -dynamodb.periodic-table.from=2030-01-01
        - -memcached.hostname={{ .Values.global.cortex.memcachedHostname }}
        - -memcached.timeout=1s
        - -memcached.service=memcache
        - -store.index-cache-validity={{ .Values.global.store.index_cache_validity }}
        - -store.index-cache-write.memcached.hostname={{ .Values.global.cortex.memcachedWriteHostname }}
        - -store.index-cache-write.memcached.timeout=1s
        - -store.index-cache-write.memcached.service=memcache
        - -store.index-cache-write.memcached.batchsize=10000
        - -store.index-cache-write.memcache.write-back-buffer=1000000
        - -store.index-cache-read.memcached.hostname={{ .Values.global.cortex.memcachedReadHostname }}
        - -store.index-cache-read.memcached.timeout=1s
        - -store.index-cache-read.memcached.service=memcache
        - -store.index-cache-read.memcached.batchsize=10000
        - -store.index-cache-read.memcache.write-back-buffer=1000000
        - -store.cardinality-cache-size=10000
        - -store.min-chunk-age={{ .Values.global.store.min_chunk_age }}
        - -validation.reject-old-samples={{ .Values.global.validation.reject_old_samples }}
        - -cache.enable-fifocache=true
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ring
            port: http
        readinessProbe:
          httpGet:
            path: /ring
            port: http
        resources:
          {{- toYaml .Values.ruler.resources | nindent 10 }}
      {{- with .Values.ruler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.ruler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ruler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
