{{- if .Values.table_manager.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.fullname" . }}-table-manager
  labels:
    app.kubernetes.io/name: {{ include "cortex.name" . }}
    helm.sh/chart: {{ include "cortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: table-manager
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.table_manager.service.type }}
  ports:
  - port: {{ .Values.table_manager.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- if .Values.table_manager.servicemonitor.enabled }}
  - port: {{ .Values.table_manager.servicemonitor.port }}
    targetPort: http
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "cortex.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: table-manager
{{- end }}
