apiVersion: v1
name: customizable-servicemonitor
version: 0.1.0
appVersion: "0"
description: customizable servicemonitor resource dor monitoring with prometheus needed services
home: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md
