apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oidc-static.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oidc-static.name" . }}
    helm.sh/chart: {{ include "oidc-static.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  default.conf: |
    server {
      listen 80 default_server;
      listen [::]:80 default_server;

      access_log /dev/stdout;

      root /ext/static;

      index index.html;

      location / {
        try_files $uri $uri/ =404;
      }
    }
