apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oidc-static.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oidc-static.name" . }}
    helm.sh/chart: {{ include "oidc-static.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oidc-static.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oidc-static.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: "{{ .Values.image.init.repository }}:{{ .Values.image.init.tag }}"
          imagePullPolicy: {{ .Values.image.init.pullPolicy }}
          command:
            - rsync
            - -avhHP
            - /static/
            - /ext/static/
          volumeMounts:
            - mountPath: /ext/static/
              name: static
          resources:
            {{- toYaml .Values.resources.init | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /ext/static
              name: static
            - mountPath: /etc/nginx/conf.d/default.conf
              name: default-conf
              subPath: default.conf
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
      volumes:
        - name: static
          emptyDir: {}
        - name: default-conf
          configMap:
            name: {{ include "oidc-static.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
