replicas: 1
image: "anchorfree/ssl-watch:v1.1.0"
aws_key: ""
aws_secret: ""
port: "9105"
env:
- name: SSLWATCH_CONFIG_DIR
  value: "s3://some-s3-bucket/ssl-watch"
- name: SSLWATCH_AUTO_RELOAD
  value: "true"
sslwatchConfig: ""
nodeAffinity: {}
tolerations: []
